### ISSUE TITLE
String tags instead of empty "tag" components?

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#14]
Would you consider adding a possibility to add tags to entities ?

Sometimes you just want to mark an entity as having a certain feature and then target those entities in systems. As it stands currently you have to create an empty pseudo-component just to slap it on an entity as a form of marker or a tag.  If such tags could be implemented as a list of strings (or even constant integers) it could possibly save some compile time, some unnecessary files, and would be a wee bit more data-driven friendly. Targeting would possibly resolve quicker as well.

**Comment by grofit** [comment]
The idea sounds good and I am open to it, however it can make groups more confusing and what if you have a tag (which may be short hand for "it is a player" but you haven't actually applied the right components), at least with the groups concept in the ECS world you are basically using the components on the entity as the contract, so I still want this to be paramount, the components are the things that you should be selecting on.

However I do see that it could be useful to tag entities in some way so you can quickly refer to them in pools, I could do with some other opinions on the concept before I go and implement it, as currently you _can_ have this sort of behaviour by just having a `TaggedComponent` which contains all the tags, and you just have a group which has a predicate for the tags you want, but it is not as succinct.

Anyway let me have a chat with some others and get their thoughts, can you also provide a couple of _real world_ use cases for this feature? just so I can get a more clear idea on how it would be used (so I know it is not going to be used by people as a rope to hang themselves).

**Comment by gregee123** [comment]
I never said adding tags meant ousting groups.

var group = new GroupBuilder()
    .WithComponent<SomeActualNonEmptyComponent>()
    .WithTag(string ) // or maybe int as it'll work faster
    .Build();

TagComponent and predicate is one way to do it but WithTag() is cleaner and potentially more data-driven friendly.

**Comment by grofit** [comment]
I didn't mean that Tags would replace groups, I expected them to work exactly like you show above, where a group is aware of tags and would use that in the constraining logic, however my worry was that if you did something like above:

```
var group = new GroupBuilder()
.WithComponent()
.WithTag("my-tag")
.Build();
```

If a system uses this tag, what components is it expecting to be applied to the entity?

Generally you would have the components set as the contract so you know your system will have AT LEAST the components you stipulate, however tags can offer you a way to bypass that notion so you could do:

```
// Will get all entities which have moveable and wander components AND a tag "npc"
var npcWithComponentsGroup = new GroupBuilder()
.WithComponent<MoveableComponent>()
.WithComponent<WanderComponent>()
.WithTag("npc")
.Build();

// Will get all entities which have tag "npc"
var npcGroup = new GroupBuilder()
.WithTag("npc")
.Build();
```

So people could use both those approaches to get the same entities, however if you use the latter you do not know for sure that those components exist on the entity in the system, so it introduces a large amount of possible user error, as you could incorrectly tag stuff, or assume because a tag is there it should be handled by a system but it may be lacking certain components, so if you were to enforce that the components you need are all there (as you would normally do with a group), there is often only a small amount of reasons you would want tagging on top of that, again if you can show some real world scenarios where these tags would be useful in groups I am more on board with implementing it, but it worries me that for most people they may use tags instead of component contracts and that would break things a lot for them.

Currently the only scenario I could see this being useful would be where you had 2 different kinds of entity which happened to have same components, i.e:

```
// Get townfolk
var townfolkGroup = new GroupBuilder()
.WithComponent<MoveableComponent>()
.WithComponent<WanderComponent>()
.WithTag("town-folk")
.Build();

// Get animals
var animalsGroup = new GroupBuilder()
.WithComponent<MoveableComponent>()
.WithComponent<WanderComponent>()
.WithTag("animals")
.Build();
```

However in _most_ cases when you have these sort of scenarios its very rare you wouldn't have some additional component on each to provide different logic, i.e killing townsfolk may yield karma or something so you would need another component to handle that. So tags seems to be a roundabout solution to an uncommon problem currently. (Again happy to be talked around with some real world examples and use-cases)

**Comment by gregee123** [comment]
If this problem was so uncommon you wouldn't have so many empty components in your examples. Tags are my suggestion only to make it possible to not have to waste time creating those empty components and that's it.

**Comment by grofit** [comment]
True I do have a lot of empty components but in most cases its because its just implying something in the example rather than doing anything real world. It is a good idea and I like the reasoning behind it, but I cannot shake the idea that it will open up the possibility of user error, but I guess like all things you need to trust the devs to be sensible.

**Comment by gregee123** [comment]
As far as possibility of error there's literally no difference between tags and empty components just saves you some hustle.

**Comment by grofit** [comment]
Empty components wouldnt match anything though, if you were to have:

```
// Empty group
var emptyGroup = new GroupBuilder().Build();

// Or the actual EmptyGroup for manual systems etc
var emptyGroup = new EmptyGroup();
```

Then used that group in a system you would get 0 entities returned, however if we add tags into the equation you could get anything back.

```
// Gets npcs
var npcsGroup = new GroupBuilder().WithTag("npc").Build();
```

So the above one would basically get you NPCs but you wont have a clue what is actually applied on those entities as you are not enforcing any component contract, and that is the crux of my worries.

There is also another concern which is how you should handle multiple tags, assuming you have multiple tags applied, i.e:

```
var whatWillThisGet = new GroupBuilder().WithTags(["red", "big"]).Build();
```

I would assume it would get things which are both red AND big, however I am not sure if you envision multiple tags to be an OR relationship or an AND?

**Comment by gregee123** [comment]
I don't know why do you seem to confuse empty groups and empty components. Empty component is a component with no fields/properties.

**Comment by gregee123** [comment]
In your example you use:

return base.TargetGroup.WithComponent<CubeComponent>();

however CubeComponent is just:

```
public class CubeComponent : IComponent
{}
```

It could be replaced with a notion of a tag which would be less labor intensive

**Comment by grofit** [comment]
I don't believe there has been any confusion here:
- EmptyGroup is a group which has no components to look for in the pool, so it will yield 0 entities

So my example above is focused on this notion where you can provide an empty group and you will get nothing back, however adding tags in, a group with no components could still return stuff.

As mentioned the examples are not indicative of real world scenarios, if you have a `CubeComponent` in the real world you would probably have some data with it, like `Size`, `Colour` etc, the examples are not real world, its just academic to show intent. The closest to real world is the Roguelike example and the only applicable thing in there is `ExitComponent` which could be a tag, but adding a whole new paradigm in (which is open to abuse) just for this one niche doesnt seem worth it.

I mean if we look back through this chat, I am writing entire essays on why it can be abused, and you are doing like a sentence here and there, it would be far easier for me to just agree and be done with it and implement it, but I feel the pros it has are currently outweighed by the cons it brings with it.

**Comment by gregee123** [comment]
Like I said already there's NO difference as far as openness to abuse between tags and empty components but it is clear it's falling on deaf ears.

**Comment by grofit** [comment]
There is 100% difference, a group will bring back entities matching components, if you have no components in the group or the components do not exist then entities are not returned. So there is no abuse possible with empty groups, as you do not get anything back to abuse, and empty components have nothing to do with the crux of my problem, well maybe in a round about way they could be used in a way where you just provide that singular component as the contract but that's more developer error than abuse.

So to clarify by "Abuse" we mean a group providing a system entities it cannot action, be it missing components on an entity, or a component which has not been setup to the state you expect (via predicates).

So assuming the above term abuse is the same for both of us, then currently Groups can not be abused in the same way, as they will return back entities matching your components (and optional predicate if set), so an empty group brings back no entities so nothing for a system to process, having an empty component instead of a tag could lead to similar results but it is less likely that someone would do that.

If we add tags into this then groups can be abused in more ways as you can then get entities into systems which have a tag that you want (again you have not stipulated if tags should be an OR/AND as this has MASSIVE ramifications, which would not be apparent with the current empty component approach), but that tag does not guarantee that the entities returned have the components you require on them.

So its not falling on deaf ears, if anything I am responding and providing you as much information and context as I can around the issue. I appreciate that its frustrating suggesting something and there being resistance but there is resistance for a good reason, if you cannot see the possible pit falls of implementing this feature (Especially without further clarification on how tags would work) then there is some disconnect with our understanding of what you want here.
