### ISSUE TITLE
Vector3 in component editor doesn't work

### ISSUE THREAD

**Issue by Bezarius** [EcsRx/ecsrx.unity#34]
For reproduction:
```
public class SomeComponent : IComponent
{
    public Vector3 SomeVec{ get; set; }
}
```

On go add RegisterAsEntity and add SomeComponent.

Now in editor we can see error:

> NullReferenceException: Object reference not set to an instance of an object
> EcsRx.Json.JSONNode.set_AsVector3 (Vector3 value) (at Assets/EcsRx/Unity/JSON.cs:949)
> EcsRx.Json.JSONData..ctor (Vector3 value) (at Assets/EcsRx/Unity/JSON.cs:428)
> Assets.EcsRx.Unity.Extensions.ComponentExtensions.SerializeComponent (System.Object component) (at Assets/EcsRx/Unity/Extensions/ComponentExtensions.cs:84)
> EcsRx.Unity.Helpers.RegisterAsEntityInspector+<ComponentListings>c__AnonStorey0.<>m__0 () (at Assets/EcsRx/Unity/MonoBehaviours/Editor/RegisterAsEntityInspector.cs:86)
> EcsRx.Unity.Helpers.Extensions.EditorExtensions.UseVerticalBoxLayout (UnityEditor.Editor editor, System.Action action) (at Assets/EcsRx/Unity/MonoBehaviours/Editor/Extensions/EditorExtensions.cs:17)
> EcsRx.Unity.Helpers.RegisterAsEntityInspector.ComponentListings () (at Assets/EcsRx/Unity/MonoBehaviours/Editor/RegisterAsEntityInspector.cs:54)
> EcsRx.Unity.Helpers.RegisterAsEntityInspector.OnInspectorGUI () (at Assets/EcsRx/Unity/MonoBehaviours/Editor/RegisterAsEntityInspector.cs:137)
> UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1236)
> UnityEditor.DockArea:OnGUI()

As i understand it's incorrect implementation method for vec serialization.

**Comment by grofit** [comment]
That is an odd one, as it implies that something is null in the process, and it cannot be your Vector3 as I am pretty sure they are structs. I will take a look when I get home tonight and see if I can sort it out for you. On a side note the serialization stuff I think needs a lot of re-work, there is a branch around trying to adopt a serialisation library rather than just having this built in serializer, but then the problem is tying everyone to a specific framework... anyway if you find a solution before I do by all means do a PR if not I will take a look later.

**Comment by grofit** [comment]
This has been fixed now, until a release is done you can always just take the JSON.cs file from the master branch and replace yours, it should fix the issue.
