### ISSUE TITLE
Example with Animator

### ISSUE THREAD

**Issue by Bezarius** [EcsRx/ecsrx.unity#36]
Hi!

Could you add an example of using a simple animator(walk\attack\death)?

I would like to see an example of the correct use of ecsrx for such tasks.

**Comment by grofit** [comment]
Hi, sorry but my main laptop screen broke on friday so am using backup laptop that is a bit poo, so will not be actively doing much until thats repaired.

We can discuss the point though, and generally I dont think there is a specific way to do this, you can handle your animation wherever you want, off the top of my head I would probably have some sort of animation system which listens for events and has a component with the animator on and just switches the mechanim vars based upon that, but it completely depends upon scenario. Like if you had a complex fighting game you would probably want systems to handle the moves and each move to change the animations, you could have a system per animation type if you wanted to so for complex concerns you just listen for whatever predicate would lead you to change the animation.

Ultimately it would probably not be that much different to how you would control it all via mono behaviours etc, you would just put your logic elsewhere, or if you wanted to keep it all in MBs and just raise relvent events from a `InjectableMonoBehaviour` or whatever they are called to tell ECS that something has changed.

There are also some animator related rx methods but I think that is more for listening for animation changes (which you may want to do), but you work out how complex your scenario needs to be and then work out if you need it all in one system, in multiple systems or even just in a class or MB etc. The EcsRx framework was made to play happily with unity and MBs even if generally they should be avoided if possible (and it makes sense).

Hope that helps, my laptop should be fixed by next week so will have a go at putting together something simple then.

**Comment by grofit** [comment]
Sorry for delay, have not had much time to look at expanding the examples, and at the moment don't really have time to do so. Am happy to accept a PR or offer guidance to someone else on this, as its not really a simple "Heres how animation would be handled" as it could be done many ways, and also may be worth mentioning that I made a separate lib that supplements this one, [BindingsRx](https://github.com/grofit/bindingsrx).

You can see some extensions here that can be used for animation:

https://github.com/grofit/bindingsrx/blob/master/src/Assets/BindingsRx/Bindings/AnimatorExtensions.cs

Anyway I am flagging this as closed for now, but anyone can do a PR or re-open with more specific questions if needed.
