### ISSUE TITLE
EcsRxApplication:RegisterAllBoundSystems will process ISystem which already handle by SetupAllPluginSystems()

### ISSUE THREAD

**Issue by vvhh2002** [EcsRx/ecsrx.unity#50]
EcsRxApplication:RegisterAllBoundSystems will process ISystem which have already handled by SetupAllPluginSystems()

It's cause a error :An element with the same key already exists in the dictionary.

**Comment by vvhh2002** [comment]
I think we should distinguish ISystem  and the ISystem in IEcsPlugins, just like Entitas‘s Feature Class

**Comment by grofit** [comment]
Hey, I think there is some confusion, so there is just 1 `ISystem` interface, which is just used as a basic "This is a system" interface, realistically most people will implement the conventions ones or make their own proxy interface for the `ISystem` if they are making their own type of systems.

With this being said the purpose of `SetupDependencies` inside the Plugin class is there for you to register unique  dependencies, like if you had a `IDamageCalculator` which you wanted to be injected into your systems, or you needed to resolve the `IEventSystem` and pass that to some other dependency you may have.

The `GetSystemForRegistration` method (which should probably be GetSystem**s**ForRegistration) is there to expose any systems you want to be registered automatically, as in the main app view layer you can bind your systems via their namespace, but plugins should just pass back any systems that need to be registered in the ECS world.

At no point should you really be binding `ISystem` to anything, as that implies there is a singular representation of `ISystem` so I would avoid putting any of your systems into the DI container as the `ISystem` and instead they should be registered as their own interface type or concrete type.

If you look at https://github.com/grofit/ecsrx.buffs/blob/master/Assets/EcsRxPlugins/Buffs/BuffsPlugin.cs as an example, that whole project uses plugins and works fine.

If you can share a repro of the issue I can try to help further but generally in your plugin dont register anything as `ISystem`, as the `RegisterAllBoundSystems` is the pathway for systems inside YOUR project, the `SetupAllPluginsSystems` is the pathway for systems outside YOUR project, so they should not be registering the same systems.

It is also worth mentioning this whole system registration convention thing was thrown together quite quickly as a first attempt at how to make managing system registration easier, so that side may change in the future and hopefully will become better.

**Comment by grofit** [comment]
I am flagging this as closed, but feel free to re-open if you have any more questions.
