### ISSUE TITLE
Modernize playmode (integration) tests & upgrade to Zenject 5.4.0

### ISSUE THREAD

**Issue by fadookie** [EcsRx/ecsrx.unity#53]
[Unity test tools is deprecated](https://bitbucket.org/Unity-Technologies/unitytesttools/overview). [Zenject 5.4.0](https://github.com/modesttree/Zenject/releases/tag/v5.4.0) has added support for the [new playmode test framework](https://docs.unity3d.com/Manual/testing-editortestsrunner.html) ([API](https://docs.unity3d.com/Manual/PlaymodeTestFramework.html)).

How much work do you think it would be to upgrade to Zenject 5.4.0 to support this?

**Comment by grofit** [comment]
Hello, updating to Zenject 5.4.0 should be fine, I have not looked at it but shouldn't take too long to do, will look at doing it when I get back home.

## Just on a note about the new unity test stuff.

Currently the unity test framework causes numerous issues with testing outside of unity, i.e all the tests in this framework can only be run within unity, if you attempt to run them in an external runner (which used to work fine in previous unity versions before their new version) it will fail as unity package a custom nunit.dll which is incompatible with any nunit/test runner plugins/tools outside of the unity ide :(

(Rider has a workaround for this, but none of the others do :( )

**Comment by fadookie** [comment]
@grofit Awesome! Let me know if you need/want help with this. I am looking for a framework that will allow me to do DI, mocking/testing and use UniRx and EcsRx looks like a good fit. I'm also looking to integrate with UNET for multiplayer so that should be an interesting exercise. :D

**Comment by grofit** [comment]
That is one reason I did this framework, to make automation testing easier and putting in some sensible design patterns along the way, such as IoC, DI and I like the reactivity of Rx, so hopefully it should tick most of the boxes that you want. If you want to discuss more feel free to go on the gitter channel.

**Comment by grofit** [comment]
Done most of the changes, but the new unity test guff breaks unit tests as I said... so you cant run them outside of unity... that may seem fine, just run them in unity. The problem then is that NSubstitute used to come with unity test tools, which is now defunct. 

So then if you think *HUZZAH* I can go download it from nuget, you *CAN* get a 3.5 compatible version, but then unity shits the bed because it doesnt support `Emit` on reflection stuff which is what the default .net 3.5 version uses...

So anyway long story short, cannot run any tests now, waiting for some of the unity chappies to give me some guidance on how to mitigate this issue, as I am not too comfortable releasing the new version without without having all tests running and passing, although scenes seem to work fine.

**Comment by grofit** [comment]
If you need it urgently there is a branch which has all the changes:

https://github.com/grofit/ecsrx/tree/zenject-unity-update

Like I say wont be releasing it officially until I can get testing running and passing again.

**Comment by fadookie** [comment]
@grofit Awesome, thanks so much!

In the long term perhaps it would be possible to replace with Moq?

For now, could you grab the old NSubstitute dll from unity test tools distribution?

**Comment by grofit** [comment]
Yeah could go, I just find Moq slightly more of a chore to work with, but there was some chatter on the subject on the unity devs slack in the testing channel, and going forward the testing area may change a bit, so for the moment will just try hacking around with the old nsubstitute dll.

**Comment by grofit** [comment]
Right the release has been done for 0.11.0, I will close this although the title implies updating/modernizing the tests in the library. So that is not something I am looking to bite off at the moment, so if you or someone else wants to add scene tests to verify stuff works as expected thats great and will be happy to accept a PR and a new issue to track it.

If not then the libs in the project have been updated to use the latest 3rd party ones, but I dont really think it will effect consumers as they pull in their own unirx/zenject versions anyway.

Feel free to reopen if needed.

**Comment by fadookie** [comment]
@grofit thanks - Didn't realize I had the option of supplying my own version of the dependencies, that's great.
