### ISSUE TITLE
Present a read order for docs

### ISSUE THREAD

**Issue by starikcetin** [EcsRx/ecsrx.unity#55]
It would be easier to follow the docs if there was a read order presented on the homepage.

**Comment by grofit** [comment]
Sure, currently the docs are more "here is how this bit works" rather than a tutorial style "read from start to finish and know all" so I can put a proposed order later when I have time but if anyone has any preference or wishes to add to the documents feel free to.

Its also worth mentioning the documents generally dont cover "What ECS is" or "What DI is and how you use it", which some users may like, but currently its expected people know this when coming in the door.

**Comment by grofit** [comment]
@chris1054 as mentioned above there is currently no specific "read order", components are just as important to know about as entities, and groups etc. So what you want is more of a "what is ECS" guide I think which the internet can provide in troves.

In terms of "how do I use *THIS* ECS implementation" then currently its best to look over the docs, when I get more time I am happy to do a more guided blurb on the library and what ECS is, but at the moment I simply dont have the free time to do so, and the internet can provide answers on most of the high level "what is ECS" style things.

As mentioned crack this open and look at the examples within or look at the 2d roguelike.

There is also a gitter channel where there are a people who would be more than happy to field any questions in the meantime.

**Comment by grofit** [comment]
If you look at the docs folder there is now a proposed read order.

https://github.com/EcsRx/ecsrx.unity/blob/master/docs/readme.md

The docs will change when the new alpha becomes a full release and then it would be good if the community could help with some of the documentation.

**Comment by grofit** [comment]
I am closing this as the docs have been improved on both EcsRx core and EcsRx.Unity, if you feel more is needed them I am happy for you to re-open this.
