### ISSUE TITLE
Magic extension method BindAllSystemsWithinApplicationScope

### ISSUE THREAD

**Issue by OmiCron07** [EcsRx/ecsrx.unity#63]
The extension method ``BindAllSystemsWithinApplicationScope`` do some undocumented magic. But, one major issue, it forces you to put Application classes at the parent root of the ``Systems`` and ``ViewResolvers`` folders and thus, you can't put your Application classes in their own folder.

**Comment by grofit** [comment]
I will add some documentation around this.

One thing to mention is that this does not force anything, it is a helper method for people who use a common convention, however you can easily use other helpers to just register systems in other namespaces, or just manually register your systems yourself, it is just used so much because its a common convention.

**Comment by grofit** [comment]
Have added docs for this here:

https://github.com/EcsRx/ecsrx.unity/blob/master/docs/structure-and-conventions.md

Feel free to re-open if you feel it does not cover what you need.
